appointments/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        'scheduling/',          # any path starting with this should be handled by the urls config in the this app
        include('scheduling.urls')      # specifies name of module that contains url configuration for this app
    ),
    path(
        'carsale/',
        include('carsale.urls')
    ),
    path('salestats/', include('salestats.urls'))
]

carsale/urls.py
from django.urls import path
from . import views


app_name = 'carsale'
urlpatterns = [
    path('',    # first arg we specify url endpoint; empty string represents root of this app
        views.index,
        name='index'),   # best practice, we should name these url endpoints
    path('<int:car_id>', views.detail, name='detail'),
    path('purchase/<int:car_id>',views.purchase,name='purchase')
]

salestats/urls.py
from django.urls import path
from . import views


app_name = 'salestats'
urlpatterns = [
    # path('',    # first arg we specify url endpoint; empty string represents root of this app
    #     views.index,
    #     name='index'),
    path('', views.sale_statistics, name='sale_statistics'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Car Dealership</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <div class="padding-22">
        <a class="navbar-brand mb-0 h1" href="{% url 'home' %}"
          >Car Dealership</a
        >
      </div>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% if user.is_authenticated %}
          Hi {{ user.username }}! 
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Log Out</button>
          </form>
        {% else %}
          <p>You are not logged in</p>
          <a href="{% url 'login' %}">Log In</a>
        {% endif %}
      </div>
    </nav>
    <main class="container">{% block content %} {% endblock %}</main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} 

{% block content %}
  <dl>
    <dt><a href="{% url 'carsale:index' %}">Browse Our Inventory</a></dt>
    <dd>- See what we have in stock</dd>
    <dt><a href="{% url 'salestats:sale_statistics' %}">Sales Statistics</a></dt>
    <dd>- View sales statistics by period</dd>
  </dl>
    
{% endblock %}